JOB_APPLICATION_CONFIRMATION = "Job Applied Confirmation"
JOB_REJECTION = "Job Rejection"
JOB_UNDER_CONSIDERATION = "Job Under Consideration"
JOB_OFFERED = "Job Offered"
NEW_JOB_NOTIFICATION = "New Job Notification"
NEW_JOB_TASK = "Job Task or To Do"
NOT_JOB_SPECIFIC_EMAIL = "Not Job Specific Email"

Classifications = [
    JOB_APPLICATION_CONFIRMATION,
    JOB_REJECTION,
    JOB_OFFERED,
    NEW_JOB_NOTIFICATION,
    NEW_JOB_TASK,
    NOT_JOB_SPECIFIC_EMAIL
]
